var locations = [
  'Consolación del Sur',
  'Guane',
  'Mantua',
  'Pinar del Río',
  'San Luis',
  'Viñales',
  'Los Palacios',
  'Artemisa',
  'Matanzas',
  'Cienfuegos',
  'Sancti Spiritus',
  'Ciego de Ávila',
  'Camagüey',
  'Las Tunas',
  'Holguín',
  'Santiago de Cuba',
  'Guantánamo',
  'Mariel',
  'Guanajay',
  'Bauta',
  'San Antonio de los Baños',
  'Güira de Melena',
  'Alquízar',
  'Artemisa',
  'Bahía Honda',
  'Candelaria',
  'San Cristóbal',
  'Habana',
  'Centro Habana',
  'Bejucal',
  'San José de las Lajas',
  'Jaruco',
  'Santa Cruz del Norte',
  'Madruga',
  'Melena del Sur',
  'Batabanó',
  'Quivicán',
  'Calimete',
  'Cárdenas',
  'Colón',
  'Jagüey Grande',
  'Jovellanos',
  'Los Arabos',
  'Martí',
  'Matanzas',
  'Perico',
  'Unión de Reyes',
  'Cienfuegos',
  'Cruces',
  'Palmira',
  'Rodas',
  'Abreus',
  'Aguada de pasajeros',
  'Cumanayagüa',
  'Caibarién',
  'Camajuaní',
  'Cifuentes',
  'Corralillo',
  'Encrucijada',
  'Manicaragua',
  'Placetas',
  'Quemado de Güines',
  'Remedios',
  'Sagüa la Grande',
  'Santa Clara',
  'Santo Domingo',
  'Sancti Spíritus',
  'Trinidad',
  'Cabaiguán',
  'Yaguajay',
  'Jatibonico',
  'Fomento',
  'Ciego de Ávila',
  'Morón',
  'Chambas',
  'Venezuela',
  'Baraguá',
  'Primero de Enero',
  'Camagüey',
  'Guáimaro',
  'Nuevitas',
  'Sibanicú',
  'Esmeralda',
  'Minas',
  'Florida',
  'Vertientes',
  'Santa Cruz del Sur',
  'Manatí',
  'Puerto Padre',
  'Las Tunas',
  'Jobabo',
  'Colombia',
  'Bayamo',
  'Campechuela',
  'Guisa',
  'Jiguaní',
  'Manzanillo',
  'Media Luna',
  'Niquero',
  'Río Cauto',
  'Yara',
  'Baracoa',
  'Guantánamo',
  'Contramaestre',
  'Palma Soriano',
  'San Luis',
  'Santiago de Cuba',
  'Báguanos',
  'Banes',
  'Cueto',
  'Gibara',
  'Holguín',
  'Moa',
  'Sagüa de Tánamo',
  'Buenavista',
  'Varadero',
  'El Cobre',
];
